import { Category, Draft, PickRecord, Player, PlayerBadge, Team } from '../types';
import {
  DEFAULT_BPL_LOGO,
  TEAM_DEFAULT_LOGOS,
  generateCricketAvatar,
} from './imageUtils';

export function createSampleDraftData(): {
  draft: Draft;
  categories: Category[];
  teams: Team[];
  players: Player[];
  picks: PickRecord[];
} {
  const draftId = 'bpl-s2-main';
  const now = Date.now();

  // 10 Official Categories matching the Tournament Photo with English Names
  const categories: Category[] = [
    {
      id: 'cat-bat-lvl-1',
      draftId,
      name: 'Batsman Level-01',
      color: '#2563EB',
      iconName: 'Zap',
      order: 1,
      active: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'cat-bat-lvl-2',
      draftId,
      name: 'Batsman Level-02',
      color: '#0284C7',
      iconName: 'Shield',
      order: 2,
      active: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'cat-bat-lvl-3',
      draftId,
      name: 'Batsman Level-03',
      color: '#0D9488',
      iconName: 'Flame',
      order: 3,
      active: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'cat-bat-lvl-4',
      draftId,
      name: 'Batsman Level-04',
      color: '#059669',
      iconName: 'Award',
      order: 4,
      active: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'cat-bowl-bat-equal',
      draftId,
      name: 'Bowling-Batting Equal',
      color: '#D97706',
      iconName: 'Scale',
      order: 5,
      active: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'cat-bat-all-round',
      draftId,
      name: 'Batting All-Rounder',
      color: '#EA580C',
      iconName: 'Flame',
      order: 6,
      active: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'cat-slow-bowl-all',
      draftId,
      name: 'Slow Bowling All-Rounder',
      color: '#7C3AED',
      iconName: 'RotateCw',
      order: 7,
      active: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'cat-bat-all-lvl-2',
      draftId,
      name: 'Batting All-Rounder Level-2',
      color: '#C026D3',
      iconName: 'Sparkles',
      order: 8,
      active: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'cat-bowling',
      draftId,
      name: 'Bowling',
      color: '#DC2626',
      iconName: 'Target',
      order: 9,
      active: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'cat-mini-all',
      draftId,
      name: 'Mini All-Rounder',
      color: '#4F46E5',
      iconName: 'Users',
      order: 10,
      active: true,
      createdAt: now,
      updatedAt: now,
    },
  ];

  // 6 Teams Quota: 1 per category (10 categories = 10 picks + 1 captain = 11 players per team)
  const default6Quotas: Record<string, number> = {
    'cat-bat-lvl-1': 1,
    'cat-bat-lvl-2': 1,
    'cat-bat-lvl-3': 1,
    'cat-bat-lvl-4': 1,
    'cat-bowl-bat-equal': 1,
    'cat-bat-all-round': 1,
    'cat-slow-bowl-all': 1,
    'cat-bat-all-lvl-2': 1,
    'cat-bowling': 1,
    'cat-mini-all': 1,
  };

  // The 6 Official Franchise Teams for BPL Season-2 (Matching Official Draft Graphic)
  const teams: Team[] = [
    {
      id: 'team-abd-sports',
      draftId,
      name: 'ABD SPORTS BROTHERS',
      shortName: 'ASB',
      logoUrl: TEAM_DEFAULT_LOGOS['team-abd-sports'],
      primaryColor: '#0284C7',
      secondaryColor: '#E0F2FE',
      maxPlayers: 10,
      captainPlayerId: 'player-1',
      captainName: 'Abdullah Akash',
      quotas: { ...default6Quotas },
      active: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'team-warriors',
      draftId,
      name: 'BROTHERS WARRIORS',
      shortName: 'BW',
      logoUrl: TEAM_DEFAULT_LOGOS['team-warriors'],
      primaryColor: '#DC2626',
      secondaryColor: '#FEE2E2',
      maxPlayers: 10,
      captainPlayerId: 'player-32',
      captainName: 'Shafiqul Islam',
      quotas: { ...default6Quotas },
      active: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'team-prime',
      draftId,
      name: 'PRIME BROTHERS',
      shortName: 'PB',
      logoUrl: TEAM_DEFAULT_LOGOS['team-prime'],
      primaryColor: '#D97706',
      secondaryColor: '#FEF3C7',
      maxPlayers: 10,
      captainPlayerId: 'player-20',
      captainName: 'Alauddin',
      quotas: { ...default6Quotas },
      active: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'team-fearless',
      draftId,
      name: 'FEARLESS BROTHERS',
      shortName: 'FB',
      logoUrl: TEAM_DEFAULT_LOGOS['team-fearless'],
      primaryColor: '#7C3AED',
      secondaryColor: '#EDE9FE',
      maxPlayers: 10,
      captainPlayerId: 'player-8',
      captainName: 'Sakhawat Hossain',
      quotas: { ...default6Quotas },
      active: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'team-mighty',
      draftId,
      name: 'MIGHTY BROTHERS',
      shortName: 'MB',
      logoUrl: TEAM_DEFAULT_LOGOS['team-mighty'],
      primaryColor: '#0891B2',
      secondaryColor: '#CFFAFE',
      maxPlayers: 10,
      captainPlayerId: 'player-31',
      captainName: 'AR Mukul',
      quotas: { ...default6Quotas },
      active: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'team-amra-amroi',
      draftId,
      name: 'AMRA AMROI BROTHERS ELEVEN',
      shortName: 'AABE',
      logoUrl: TEAM_DEFAULT_LOGOS['team-amra-amroi'],
      primaryColor: '#16A34A',
      secondaryColor: '#DCFCE7',
      maxPlayers: 10,
      captainPlayerId: 'player-17',
      captainName: 'Arif Khan',
      quotas: { ...default6Quotas },
      active: true,
      createdAt: now,
      updatedAt: now,
    },
  ];

  // Helper for Google Drive direct photo URLs
  const gDriveImg = (fileId: string) => `https://lh3.googleusercontent.com/d/${fileId}`;

  // Complete Roster: All 60 Players from the Photo + Registered Franchise Captains
  // Category IDs match the 10 Categories exactly
  const officialPlayersRaw: Array<{
    idKey?: string;
    fullName: string;
    bengaliName?: string;
    email?: string;
    contact?: string;
    cat: string;
    bat: 'Right Handed' | 'Left Handed';
    bowl: string;
    currentTeam?: string;
    badge: PlayerBadge;
    driveId?: string;
  }> = [
    // =========================================================================
    // SECTION 1: BATSMAN CATEGORY (ব্যাটসম্যান ক্যাটাগরি)
    // =========================================================================

    // --- Batsman Level-01 (ব্যাটসম্যান লেভেল-০১) ---
    {
      fullName: 'Abdullah Akash',
      bengaliName: 'আকাশ',
      email: 'akash.bpl@gmail.com',
      contact: '01856677832',
      cat: 'cat-bat-lvl-1',
      bat: 'Right Handed',
      bowl: 'None',
      currentTeam: 'The Crown Kings',
      badge: 'SAFE HANDS',
      driveId: '1MPM0tiBZtp0AmiN-itFYFVH3mXdQYb9o',
    },
    {
      fullName: 'Mohammad Emon',
      bengaliName: 'ইমন',
      email: 'tee279783@gmail.com',
      contact: '01516596165',
      cat: 'cat-bat-lvl-1',
      bat: 'Right Handed',
      bowl: 'None',
      currentTeam: 'The Crown Kings',
      badge: 'CLASSIC',
      driveId: '1HeTukSsjBmq68yjDQZOS3PtM7ivZwFj9',
    },
    {
      fullName: 'Rayhan Emon',
      bengaliName: 'রায়হান ইমন',
      cat: 'cat-bat-lvl-1',
      bat: 'Right Handed',
      bowl: 'Left Arm Spinner',
      badge: 'HARD HITTER',
    },
    {
      fullName: 'Jahangir',
      bengaliName: 'জাহাঙ্গীর',
      email: 'ja9771765@gmail.com',
      contact: '01609757285',
      cat: 'cat-bat-lvl-1',
      bat: 'Right Handed',
      bowl: 'Right Arm Medium',
      currentTeam: 'Prime Brothers Cricket XI',
      badge: 'ALL-ROUNDER',
      driveId: '1HKb3BnXcD6xF3R1Khv9C6y5ConN9vQr9',
    },
    {
      fullName: 'MD. Saidul Islam Polash',
      bengaliName: 'পলাশ',
      email: 'S.polash120@gmail.com',
      contact: '01972591997',
      cat: 'cat-bat-lvl-1',
      bat: 'Right Handed',
      bowl: 'Right Arm Medium',
      currentTeam: 'Prime Brothers Cricket XI',
      badge: 'SAFE HANDS',
      driveId: '10zvQ-GnfvQVntYdUJhbWrOsSvtIyrOq8',
    },
    {
      fullName: 'Mohon',
      bengaliName: 'মোহন',
      cat: 'cat-bat-lvl-1',
      bat: 'Right Handed',
      bowl: 'None',
      badge: 'CLASSIC',
    },

    // --- Batsman Level-02 (ব্যাটসম্যান লেভেল-০২) ---
    {
      fullName: 'Abran',
      bengaliName: 'আবরান',
      cat: 'cat-bat-lvl-2',
      bat: 'Right Handed',
      bowl: 'Right Arm Medium',
      badge: 'HARD HITTER',
    },
    {
      fullName: 'Sakhawat Hossain',
      bengaliName: 'শাখাওয়াত',
      email: 'sakhawat.bpl@gmail.com',
      contact: '01601998679',
      cat: 'cat-bat-lvl-2',
      bat: 'Right Handed',
      bowl: 'None',
      currentTeam: 'Prime Brothers Cricket XI',
      badge: 'CLASSIC',
      driveId: '1Js_uHDc4geX_u0o_BhiliP0vLfm4ihP',
    },
    {
      fullName: 'MD NAIEEM KHAN RONI',
      bengaliName: 'নাঈম রনি',
      email: 'naiemroni1995@gmail.com',
      contact: '01624285175',
      cat: 'cat-bat-lvl-2',
      bat: 'Right Handed',
      bowl: 'Right Arm Medium',
      currentTeam: 'Brothers Warriors',
      badge: 'HARD HITTER',
      driveId: '1AgBp6s_tJGTUGFmco5AlW_6cycAc6KnQ',
    },
    {
      fullName: 'Omar Hossain',
      bengaliName: 'ওমর',
      email: 'omar.bpl@gmail.com',
      contact: '01633522580',
      cat: 'cat-bat-lvl-2',
      bat: 'Right Handed',
      bowl: 'Right Arm Medium',
      currentTeam: 'Prime Brothers Cricket XI',
      badge: 'CLASSIC',
      driveId: '1UbezOj9-WOHL_yY1Q95lRkjqPO3lqmrL',
    },
    {
      fullName: 'Saiful Islam Antor',
      bengaliName: 'অন্তর',
      email: 'Antorn19@gmail.com',
      contact: '01944009577',
      cat: 'cat-bat-lvl-2',
      bat: 'Right Handed',
      bowl: 'None',
      currentTeam: 'The Crown Kings',
      badge: 'FINISHER',
      driveId: '1YDfFpwYX26tVPWfnlurqBvf5EBRTt7UJ',
    },
    {
      fullName: 'Shuvo',
      bengaliName: 'শুভ',
      email: 'shuvo.bpl@gmail.com',
      contact: '01829548006',
      cat: 'cat-bat-lvl-2',
      bat: 'Right Handed',
      bowl: 'None',
      currentTeam: 'The Crown Kings',
      badge: 'SAFE HANDS',
      driveId: '1GtqK9-oJXLFDlTx3HXjzO78iFdAOhw12',
    },

    // --- Batsman Level-03 (ব্যাটসম্যান লেভেল-০৩) ---
    {
      fullName: 'MD Mokka Sarker',
      bengaliName: 'মক্কা',
      email: 'mokka.bpl@gmail.com',
      contact: '01793626848',
      cat: 'cat-bat-lvl-3',
      bat: 'Right Handed',
      bowl: 'None',
      currentTeam: 'The Crown Kings',
      badge: 'GAME CHANGER',
      driveId: '1ln3WKnE0o4c2CSA3707Cg-IoZpFmH5hR',
    },
    {
      fullName: 'Shuvo Senior',
      bengaliName: 'শুভ সিনিয়র',
      cat: 'cat-bat-lvl-3',
      bat: 'Right Handed',
      bowl: 'Right Arm Medium',
      badge: 'LEADER',
    },
    {
      fullName: 'Rana Khan',
      bengaliName: 'রানা খান',
      email: 'ranakhan.bpl@gmail.com',
      contact: '01538370725',
      cat: 'cat-bat-lvl-3',
      bat: 'Right Handed',
      bowl: 'Right Arm Fast',
      currentTeam: 'Prime Brothers Cricket XI',
      badge: 'HARD HITTER',
      driveId: '1W6O9tDr3Ozonw37WmQ0NbSxM7UMNe2wD',
    },
    {
      fullName: 'Ashraful Shohel',
      bengaliName: 'আশরাফুল',
      email: 'westernmuslimabad@gmail.com',
      contact: '01833000000',
      cat: 'cat-bat-lvl-3',
      bat: 'Left Handed',
      bowl: 'Left Arm Medium',
      currentTeam: 'Brothers Warriors',
      badge: 'SAFE HANDS',
      driveId: '1D_yJhVBeGbpe2YxnoceYzMoRQ-7suTME',
    },
    {
      fullName: 'Arif Khan',
      bengaliName: 'আরিফ খান',
      cat: 'cat-bat-lvl-3',
      bat: 'Right Handed',
      bowl: 'Right Arm Medium',
      badge: 'CLASSIC',
    },
    {
      fullName: 'Nazim (Zahid)',
      bengaliName: 'নাজিম (জাহিদ)',
      cat: 'cat-bat-lvl-3',
      bat: 'Right Handed',
      bowl: 'Right Arm Medium',
      badge: 'HARD HITTER',
    },

    // --- Batsman Level-04 (ব্যাটসম্যান লেভেল-০৪) ---
    {
      fullName: 'Shahriar Alom Rafin',
      bengaliName: 'শাহরিয়ার',
      email: 'rafinff262@gmail.com',
      contact: '01761148580',
      cat: 'cat-bat-lvl-4',
      bat: 'Right Handed',
      bowl: 'None',
      currentTeam: 'Prime Brothers Cricket XI',
      badge: 'FINISHER',
      driveId: '1MJXgaleOYS7Nzx41bl8gGpo0Z8vPwydr',
    },
    {
      fullName: 'Alauddin',
      bengaliName: 'আলাউদ্দিন',
      cat: 'cat-bat-lvl-4',
      bat: 'Right Handed',
      bowl: 'Right Arm Medium',
      badge: 'CLASSIC',
    },
    {
      fullName: 'Alal',
      bengaliName: 'আলাল',
      cat: 'cat-bat-lvl-4',
      bat: 'Right Handed',
      bowl: 'Right Arm Medium',
      badge: 'HARD HITTER',
    },
    {
      fullName: 'Md. Sohanur Rohman',
      bengaliName: 'সোহান',
      email: 'sohanur.bpl@gmail.com',
      contact: '01781292912',
      cat: 'cat-bat-lvl-4',
      bat: 'Right Handed',
      bowl: 'Left Arm Spinner',
      currentTeam: 'The Crown Kings',
      badge: 'SAFE HANDS',
      driveId: '15iAEG1x0dkH1Jj7ebtADIf5V7Epcb3ec',
    },
    {
      fullName: 'Selim Badsha',
      bengaliName: 'সেলিম',
      email: 'selimbadsha@gmail.com',
      contact: '01893249247',
      cat: 'cat-bat-lvl-4',
      bat: 'Right Handed',
      bowl: 'None',
      currentTeam: 'Brothers Warriors',
      badge: 'LEADER',
      driveId: '14RQjdJyRFc1nzWwf_7JS--Jod8Pr7wll',
    },
    {
      fullName: 'Rana',
      bengaliName: 'রানা',
      email: 'rana.bpl@gmail.com',
      contact: '01810760541',
      cat: 'cat-bat-lvl-4',
      bat: 'Right Handed',
      bowl: 'None',
      currentTeam: 'Brothers Warriors',
      badge: 'HARD HITTER',
      driveId: '1RAjVOWfPnr_6M8rBfI7fxcaAvsaVWGcU',
    },

    // =========================================================================
    // SECTION 2: ALL-ROUNDER CATEGORY (অলরাউন্ডার ক্যাটাগরি)
    // =========================================================================

    // --- Bowling-Batting Equal (বোলিং-ব্যাটিং সমান) ---
    {
      fullName: 'M. Fahim',
      bengaliName: 'ফাহিম',
      email: 'fahim.bpl@gmail.com',
      contact: '01619416644',
      cat: 'cat-bowl-bat-equal',
      bat: 'Right Handed',
      bowl: 'Right Arm Fast',
      currentTeam: 'The Crown Kings',
      badge: 'WICKET TAKER',
      driveId: '13JzBDxajVFjNJKPU4-JJoZsFXAuolIiN',
    },
    {
      fullName: 'Khalek',
      bengaliName: 'খালেক',
      cat: 'cat-bowl-bat-equal',
      bat: 'Right Handed',
      bowl: 'Right Arm Fast',
      badge: 'ALL-ROUNDER',
    },
    {
      fullName: 'Sohrab Ahmed Ayan',
      bengaliName: 'অয়ন',
      email: 'sohrab.bpl@gmail.com',
      contact: '01607126226',
      cat: 'cat-bowl-bat-equal',
      bat: 'Right Handed',
      bowl: 'Right Arm Fast',
      currentTeam: 'Brothers Warriors',
      badge: 'HARD HITTER',
      driveId: '1cvUjrQDOuYJhQRiaMW90jy4DNgZrceeJ',
    },
    {
      fullName: 'Hasan',
      bengaliName: 'হাসান',
      cat: 'cat-bowl-bat-equal',
      bat: 'Right Handed',
      bowl: 'Right Arm Medium',
      badge: 'ALL-ROUNDER',
    },
    {
      fullName: 'Tanzim',
      bengaliName: 'তানজিম',
      cat: 'cat-bowl-bat-equal',
      bat: 'Right Handed',
      bowl: 'Right Arm Medium',
      badge: 'GAME CHANGER',
    },
    {
      fullName: 'RA Apon',
      bengaliName: 'আপন',
      email: 'apon06canva@gmail.com',
      contact: '01816462090',
      cat: 'cat-bowl-bat-equal',
      bat: 'Right Handed',
      bowl: 'Right Arm Medium',
      currentTeam: 'The Crown Kings',
      badge: 'GAME CHANGER',
      driveId: '1L3FV6OQEIazz1beEm0THSUSM2WCiHJa7',
    },

    // --- Batting All-Rounder (ব্যাটিং অলরাউন্ডার) ---
    {
      fullName: 'AR Mukul',
      bengaliName: 'মুকুল',
      email: 'ar.mukul@gmail.com',
      contact: '01673640084',
      cat: 'cat-bat-all-round',
      bat: 'Right Handed',
      bowl: 'Right Arm Medium',
      currentTeam: 'Brothers Warriors',
      badge: 'LEADER',
      driveId: '1ObOKZ9dU7teNp_x5purMBThWxZZZc-0Q',
    },
    {
      fullName: 'Shafiqul Islam',
      bengaliName: 'শফিক',
      email: 'shafiquldesigner57@gmail.com',
      contact: '01942068764',
      cat: 'cat-bat-all-round',
      bat: 'Right Handed',
      bowl: 'Right Arm Medium',
      currentTeam: 'Brothers Warriors',
      badge: 'ALL-ROUNDER',
      driveId: '1OkTbsfwNnfunsUOl68tGCl-YKYtwtcPs',
    },
    {
      fullName: 'Zoni Ahmed',
      bengaliName: 'জনি-২',
      email: 'zoniahmed15@gmail.com',
      contact: '01833-081331',
      cat: 'cat-bat-all-round',
      bat: 'Right Handed',
      bowl: 'Right Arm Fast',
      currentTeam: 'Prime Brothers Cricket XI',
      badge: 'GAME CHANGER',
      driveId: '1mkIXYh7Pq5qPxs5-y_8FfpeqdsZlAHOP',
    },
    {
      fullName: 'Rezvi',
      bengaliName: 'রেজভি',
      email: 'greenglow214@gmail.com',
      contact: '01791168132',
      cat: 'cat-bat-all-round',
      bat: 'Right Handed',
      bowl: 'Right Arm Medium',
      currentTeam: 'Prime Brothers Cricket XI',
      badge: 'ALL-ROUNDER',
      driveId: '1ORK70NaWvB6k--fHSTc2IsS3HYNEC_4B',
    },
    {
      fullName: 'Mehedi Hasan Mithun',
      bengaliName: 'মিঠুন',
      email: 'mehedihasan20333@gmail.com',
      contact: '01882670212',
      cat: 'cat-bat-all-round',
      bat: 'Right Handed',
      bowl: 'Right Arm Medium',
      currentTeam: 'Brothers Warriors',
      badge: 'ALL-ROUNDER',
      driveId: '1KTaY5hLg06GSUa_PqndXPn5lErlMJvO9',
    },
    {
      fullName: 'Sujan',
      bengaliName: 'সুজন',
      cat: 'cat-bat-all-round',
      bat: 'Right Handed',
      bowl: 'Right Arm Medium',
      badge: 'ALL-ROUNDER',
    },

    // --- Slow Bowling All-Rounder (স্লো বোলিং অলরাউন্ডার) ---
    {
      fullName: 'Arif Iquebal',
      bengaliName: 'আরিফ ইকবাল',
      email: 'arif.bpl@gmail.com',
      contact: '01878113798',
      cat: 'cat-slow-bowl-all',
      bat: 'Right Handed',
      bowl: 'Right Arm Medium',
      currentTeam: 'Brothers Warriors',
      badge: 'GAME CHANGER',
      driveId: '1Qigba-LT2bTDAGLw9Iozc785a4-PUPDv',
    },
    {
      fullName: 'Sohag',
      bengaliName: 'সোহাগ',
      cat: 'cat-slow-bowl-all',
      bat: 'Right Handed',
      bowl: 'Right Arm Off Spin',
      badge: 'ALL-ROUNDER',
    },
    {
      fullName: 'Y.A. Jony',
      bengaliName: 'জনি',
      email: 'ya.jony@gmail.com',
      contact: '01934594920',
      cat: 'cat-slow-bowl-all',
      bat: 'Right Handed',
      bowl: 'Right Arm Medium',
      currentTeam: 'Prime Brothers Cricket XI',
      badge: 'ALL-ROUNDER',
      driveId: '1w7u4bM1H6XVI83z4v0qWu0redwRDnlS8',
    },
    {
      fullName: 'Khorshed',
      bengaliName: 'খোরশেদ',
      cat: 'cat-slow-bowl-all',
      bat: 'Right Handed',
      bowl: 'Right Arm Off Spin',
      badge: 'ALL-ROUNDER',
    },
    {
      fullName: 'Shamim Islam',
      bengaliName: 'শামিম',
      email: 'shamim.bpl@gmail.com',
      contact: '01904174565',
      cat: 'cat-slow-bowl-all',
      bat: 'Right Handed',
      bowl: 'Right Arm Fast',
      currentTeam: 'Brothers Warriors',
      badge: 'WICKET TAKER',
      driveId: '1mVq2nz1fCRo5MlpwZlEYMwabLWkAuMR8',
    },
    {
      fullName: 'Abdullah Al Mamun',
      bengaliName: 'মামুন',
      email: 'mamun.bpl@gmail.com',
      contact: '01815892290',
      cat: 'cat-slow-bowl-all',
      bat: 'Right Handed',
      bowl: 'Right Arm Medium',
      currentTeam: 'The Crown Kings',
      badge: 'ALL-ROUNDER',
      driveId: '1m4N_j9MPlfV6KclND6gz5LyFmUWIjdj7',
    },

    // --- Batting All-Rounder Level-2 (ব্যাটিং অলরাউন্ডার লেভেল-২) ---
    {
      fullName: 'LKD Sadek',
      bengaliName: 'সাদেক',
      email: 'sadek.bpl@gmail.com',
      contact: '01407656394',
      cat: 'cat-bat-all-lvl-2',
      bat: 'Right Handed',
      bowl: 'Right Arm Medium',
      currentTeam: 'Brothers Warriors',
      badge: 'DESTROYER',
      driveId: '109FYXUU8aXVClrxt5q4ayfD4tGenDcTS',
    },
    {
      fullName: 'Roni Khan',
      bengaliName: 'রনি খান',
      email: 'ronikhan.bpl@gmail.com',
      contact: '01753146250',
      cat: 'cat-bat-all-lvl-2',
      bat: 'Right Handed',
      bowl: 'Right Arm Fast',
      currentTeam: 'Brothers Warriors',
      badge: 'HARD HITTER',
      driveId: '1L707lXwXWm0coC9RWYEWfb54qz0abm6A',
    },
    {
      fullName: 'RS Rafiq',
      bengaliName: 'আর এস রফিক',
      email: 'rsboy8437@gmail.com',
      contact: '01679531737',
      cat: 'cat-bat-all-lvl-2',
      bat: 'Right Handed',
      bowl: 'Right Arm Medium',
      currentTeam: 'Brothers Warriors',
      badge: 'ALL-ROUNDER',
      driveId: '16DNMC7FhULPd6dKbpJVtAnaycAHjr-Rq',
    },
    {
      fullName: 'Tusher Hossain',
      bengaliName: 'তুষার',
      email: 'tusher.bpl@gmail.com',
      contact: '01855490339',
      cat: 'cat-bat-all-lvl-2',
      bat: 'Right Handed',
      bowl: 'Right Arm Medium',
      currentTeam: 'Brothers Warriors',
      badge: 'ALL-ROUNDER',
      driveId: '1JMaNSfa2W_k-zauo1ye5eijF6IIJtE5z',
    },
    {
      fullName: 'Jahangir (2)',
      bengaliName: 'জাহাঙ্গীর (২)',
      cat: 'cat-bat-all-lvl-2',
      bat: 'Right Handed',
      bowl: 'Right Arm Medium',
      badge: 'ALL-ROUNDER',
    },
    {
      fullName: 'HK RONY',
      bengaliName: 'এইচ.কে রনি',
      email: 'hkrony62@gmail.com',
      contact: '01613049526',
      cat: 'cat-bat-all-lvl-2',
      bat: 'Right Handed',
      bowl: 'Right Arm Medium',
      currentTeam: 'Prime Brothers Cricket XI',
      badge: 'ALL-ROUNDER',
      driveId: '1qMrXJGidUBuw6YgHtxvIANLPCc5dELhd',
    },

    // =========================================================================
    // SECTION 3: BOWLER AND MINI ALL-ROUNDER (বোলার এবং মিনি অলরাউন্ডার)
    // =========================================================================

    // --- Bowling (বোলিং) ---
    {
      idKey: 'player-asif',
      fullName: 'Asif',
      bengaliName: 'আসিফ',
      email: 'asif.bpl@gmail.com',
      contact: '01623992742',
      cat: 'cat-bowling',
      bat: 'Right Handed',
      bowl: 'Right Arm Fast',
      currentTeam: 'Brothers Warriors',
      badge: 'WICKET TAKER',
      driveId: '1ib3APQq_M9FwAjAiXUIFJES8M_R6hoFd',
    },
    {
      idKey: 'player-mostafiz',
      fullName: 'Md. Mostafizur Rahman',
      bengaliName: 'মোস্তাফিজ',
      email: 'smrocky176@gmail.com',
      contact: '01618214165',
      cat: 'cat-bowling',
      bat: 'Right Handed',
      bowl: 'Right Arm Medium',
      currentTeam: 'The Crown Kings',
      badge: 'DESTROYER',
      driveId: '1RMBb60fpqWvOq9uXXe_riBtN_qT-878e',
    },
    {
      fullName: 'Nahid',
      bengaliName: 'নাহিদ',
      cat: 'cat-bowling',
      bat: 'Right Handed',
      bowl: 'Right Arm Fast',
      badge: 'WICKET TAKER',
    },
    {
      fullName: 'Rifat',
      bengaliName: 'রিফাত',
      cat: 'cat-bowling',
      bat: 'Right Handed',
      bowl: 'Right Arm Fast',
      badge: 'WICKET TAKER',
    },
    {
      fullName: 'Sabbir',
      bengaliName: 'সাব্বির',
      cat: 'cat-bowling',
      bat: 'Right Handed',
      bowl: 'Right Arm Fast',
      badge: 'WICKET TAKER',
    },
    {
      fullName: 'FH Noman',
      bengaliName: 'নোমান',
      email: 'mdnomanahmed16@gmail.com',
      contact: '01857697069',
      cat: 'cat-bowling',
      bat: 'Right Handed',
      bowl: 'Right Arm Fast',
      currentTeam: 'The Crown Kings',
      badge: 'WICKET TAKER',
      driveId: '19IZKmuyBlfmeOL1Iu_UaZ56-3mTp7Iyt',
    },

    // --- Mini All-Rounder (মিনি অলরাউন্ডার) ---
    {
      fullName: 'Raja',
      bengaliName: 'রাজা',
      cat: 'cat-mini-all',
      bat: 'Right Handed',
      bowl: 'Right Arm Medium',
      badge: 'ALL-ROUNDER',
    },
    {
      fullName: 'Robiul',
      bengaliName: 'রবিউল',
      cat: 'cat-mini-all',
      bat: 'Right Handed',
      bowl: 'Right Arm Medium',
      badge: 'GAME CHANGER',
    },
    {
      fullName: 'M Saiful',
      bengaliName: 'সাইফুল',
      email: 'saiful.bpl@gmail.com',
      contact: '01740705002',
      cat: 'cat-mini-all',
      bat: 'Right Handed',
      bowl: 'Right Arm Fast',
      currentTeam: 'The Crown Kings',
      badge: 'WICKET TAKER',
      driveId: '1gSX5kQvd_gEsPFW2SJ0NLhflLvCH5dJi',
    },
    {
      fullName: 'Jahangir (MH)',
      bengaliName: 'জাহাঙ্গীর (MH)',
      cat: 'cat-mini-all',
      bat: 'Right Handed',
      bowl: 'Right Arm Medium',
      badge: 'ALL-ROUNDER',
    },
    {
      fullName: 'Mohammad Nazim',
      bengaliName: 'নাজিম',
      email: 'theking187049@gmail.com',
      contact: '01797591183',
      cat: 'cat-mini-all',
      bat: 'Right Handed',
      bowl: 'None',
      currentTeam: 'Brothers Warriors',
      badge: 'FINISHER',
      driveId: '1XQ0GYCIRvmMWxdn8bxnnTD6TY8stwl6R',
    },
    {
      fullName: 'Monjurul Islam',
      bengaliName: 'মঞ্জুরুল',
      email: 'monjurulcakari@gmail.com',
      contact: '01776651356',
      cat: 'cat-mini-all',
      bat: 'Right Handed',
      bowl: 'Right Arm Fast',
      currentTeam: 'Prime Brothers Cricket XI',
      badge: 'ALL-ROUNDER',
      driveId: '1A9ryMX8z2QCp_OnG5y8wRvnP-wO5ATFJ',
    },

    // --- Official Franchise Captain (Retained) ---
    {
      idKey: 'player-shahin',
      fullName: 'Kazi Shahin',
      bengaliName: 'কাজী শাহিন',
      email: 'kazishahin511@gmail.com',
      contact: '01303768427',
      cat: 'cat-bowl-bat-equal',
      bat: 'Right Handed',
      bowl: 'Right Arm Medium',
      currentTeam: 'Prime Brothers Cricket XI',
      badge: 'CAPTAIN',
      driveId: '1cecWfr-TIMYwQ4lwQWSWVQoOldvdvf7t',
    },
  ];

  // 60 Official Picks reflecting the BPL Season-2 Draft Graphic & Final Roster
  const season2PicksOrder: Array<{
    seq: number;
    fullName: string;
    teamId: string;
    catId: string;
    isCaptain?: boolean;
    isWk?: boolean;
  }> = [
    // --- Round 1: Batsman Level-01 ---
    { seq: 1, fullName: 'Abdullah Akash', teamId: 'team-abd-sports', catId: 'cat-bat-lvl-1', isCaptain: true, isWk: true },
    { seq: 2, fullName: 'Mohammad Emon', teamId: 'team-warriors', catId: 'cat-bat-lvl-1' },
    { seq: 3, fullName: 'Jahangir', teamId: 'team-prime', catId: 'cat-bat-lvl-1' },
    { seq: 4, fullName: 'MD. Saidul Islam Polash', teamId: 'team-fearless', catId: 'cat-bat-lvl-1', isWk: true },
    { seq: 5, fullName: 'Rayhan Emon', teamId: 'team-mighty', catId: 'cat-bat-lvl-1', isWk: true },
    { seq: 6, fullName: 'Mohon', teamId: 'team-amra-amroi', catId: 'cat-bat-lvl-1', isWk: true },

    // --- Round 2: Batsman Level-02 ---
    { seq: 7, fullName: 'MD NAIEEM KHAN RONI', teamId: 'team-abd-sports', catId: 'cat-bat-lvl-2' },
    { seq: 8, fullName: 'Saiful Islam Antor', teamId: 'team-warriors', catId: 'cat-bat-lvl-2' },
    { seq: 9, fullName: 'Omar Hossain', teamId: 'team-prime', catId: 'cat-bat-lvl-2' },
    { seq: 10, fullName: 'Sakhawat Hossain', teamId: 'team-fearless', catId: 'cat-bat-lvl-2', isCaptain: true },
    { seq: 11, fullName: 'Abran', teamId: 'team-mighty', catId: 'cat-bat-lvl-2' },
    { seq: 12, fullName: 'Shuvo', teamId: 'team-amra-amroi', catId: 'cat-bat-lvl-2' },

    // --- Round 3: Batsman Level-03 ---
    { seq: 13, fullName: 'Nazim (Zahid)', teamId: 'team-abd-sports', catId: 'cat-bat-lvl-3' },
    { seq: 14, fullName: 'Rana Khan', teamId: 'team-warriors', catId: 'cat-bat-lvl-3' },
    { seq: 15, fullName: 'Ashraful Shohel', teamId: 'team-prime', catId: 'cat-bat-lvl-3' },
    { seq: 16, fullName: 'MD Mokka Sarker', teamId: 'team-fearless', catId: 'cat-bat-lvl-3' },
    { seq: 17, fullName: 'Shuvo Senior', teamId: 'team-mighty', catId: 'cat-bat-lvl-3' },
    { seq: 18, fullName: 'Arif Khan', teamId: 'team-amra-amroi', catId: 'cat-bat-lvl-3', isCaptain: true },

    // --- Round 4: Batsman Level-04 ---
    { seq: 19, fullName: 'Rana', teamId: 'team-abd-sports', catId: 'cat-bat-lvl-4' },
    { seq: 20, fullName: 'Alal', teamId: 'team-warriors', catId: 'cat-bat-lvl-4' },
    { seq: 21, fullName: 'Alauddin', teamId: 'team-prime', catId: 'cat-bat-lvl-4', isCaptain: true, isWk: true },
    { seq: 22, fullName: 'Md. Sohanur Rohman', teamId: 'team-fearless', catId: 'cat-bat-lvl-4' },
    { seq: 23, fullName: 'Shahriar Alom Rafin', teamId: 'team-mighty', catId: 'cat-bat-lvl-4' },
    { seq: 24, fullName: 'Selim Badsha', teamId: 'team-amra-amroi', catId: 'cat-bat-lvl-4' },

    // --- Round 5: Bowling-Batting Equal ---
    { seq: 25, fullName: 'RA Apon', teamId: 'team-abd-sports', catId: 'cat-bowl-bat-equal' },
    { seq: 26, fullName: 'Tanzim', teamId: 'team-warriors', catId: 'cat-bowl-bat-equal' },
    { seq: 27, fullName: 'Hasan', teamId: 'team-prime', catId: 'cat-bowl-bat-equal' },
    { seq: 28, fullName: 'Sohrab Ahmed Ayan', teamId: 'team-fearless', catId: 'cat-bowl-bat-equal' },
    { seq: 29, fullName: 'M. Fahim', teamId: 'team-mighty', catId: 'cat-bowl-bat-equal' },
    { seq: 30, fullName: 'Khalek', teamId: 'team-amra-amroi', catId: 'cat-bowl-bat-equal' },

    // --- Round 6: Batting All-Rounder ---
    { seq: 31, fullName: 'Rezvi', teamId: 'team-abd-sports', catId: 'cat-bat-all-round' },
    { seq: 32, fullName: 'Shafiqul Islam', teamId: 'team-warriors', catId: 'cat-bat-all-round', isCaptain: true },
    { seq: 33, fullName: 'Mehedi Hasan Mithun', teamId: 'team-prime', catId: 'cat-bat-all-round' },
    { seq: 34, fullName: 'Zoni Ahmed', teamId: 'team-fearless', catId: 'cat-bat-all-round' },
    { seq: 35, fullName: 'AR Mukul', teamId: 'team-mighty', catId: 'cat-bat-all-round', isCaptain: true },
    { seq: 36, fullName: 'Sujan', teamId: 'team-amra-amroi', catId: 'cat-bat-all-round' },

    // --- Round 7: Slow Bowling All-Rounder ---
    { seq: 37, fullName: 'Abdullah Al Mamun', teamId: 'team-abd-sports', catId: 'cat-slow-bowl-all' },
    { seq: 38, fullName: 'Shamim Islam', teamId: 'team-warriors', catId: 'cat-slow-bowl-all' },
    { seq: 39, fullName: 'Sohag', teamId: 'team-prime', catId: 'cat-slow-bowl-all' },
    { seq: 40, fullName: 'Arif Iquebal', teamId: 'team-fearless', catId: 'cat-slow-bowl-all' },
    { seq: 41, fullName: 'Khorshed', teamId: 'team-mighty', catId: 'cat-slow-bowl-all' },
    { seq: 42, fullName: 'Y.A. Jony', teamId: 'team-amra-amroi', catId: 'cat-slow-bowl-all' },

    // --- Round 8: Batting All-Rounder Level-2 ---
    { seq: 43, fullName: 'Tusher Hossain', teamId: 'team-abd-sports', catId: 'cat-bat-all-lvl-2' },
    { seq: 44, fullName: 'Rony Khan', teamId: 'team-warriors', catId: 'cat-bat-all-lvl-2' },
    { seq: 45, fullName: 'Jahangir (2)', teamId: 'team-prime', catId: 'cat-bat-all-lvl-2' },
    { seq: 46, fullName: 'HK RONY', teamId: 'team-fearless', catId: 'cat-bat-all-lvl-2' },
    { seq: 47, fullName: 'LKD Sadek', teamId: 'team-mighty', catId: 'cat-bat-all-lvl-2' },
    { seq: 48, fullName: 'RS Rafiq', teamId: 'team-amra-amroi', catId: 'cat-bat-all-lvl-2' },

    // --- Round 9: Bowling ---
    { seq: 49, fullName: 'Asif', teamId: 'team-abd-sports', catId: 'cat-bowling' },
    { seq: 50, fullName: 'Md. Mostafizur Rahman', teamId: 'team-warriors', catId: 'cat-bowling' },
    { seq: 51, fullName: 'Rifat', teamId: 'team-prime', catId: 'cat-bowling' },
    { seq: 52, fullName: 'Nahid', teamId: 'team-fearless', catId: 'cat-bowling' },
    { seq: 53, fullName: 'Sabbir', teamId: 'team-mighty', catId: 'cat-bowling' },
    { seq: 54, fullName: 'FH Noman', teamId: 'team-amra-amroi', catId: 'cat-bowling' },

    // --- Round 10: Mini All-Rounder ---
    { seq: 55, fullName: 'Mohammad Nazim', teamId: 'team-abd-sports', catId: 'cat-mini-all' },
    { seq: 56, fullName: 'Monjurul Islam', teamId: 'team-warriors', catId: 'cat-mini-all' },
    { seq: 57, fullName: 'M Saiful', teamId: 'team-prime', catId: 'cat-mini-all' },
    { seq: 58, fullName: 'Raja', teamId: 'team-fearless', catId: 'cat-mini-all' },
    { seq: 59, fullName: 'Robiul', teamId: 'team-mighty', catId: 'cat-mini-all' },
    { seq: 60, fullName: 'Jahangir (MH)', teamId: 'team-amra-amroi', catId: 'cat-mini-all' },
  ];

  const players: Player[] = officialPlayersRaw.map((raw, idx) => {
    const jerseyStr = String(idx + 1).padStart(2, '0');
    const playerId = raw.idKey || `player-${idx + 1}`;
    const photo = raw.driveId ? gDriveImg(raw.driveId) : generateCricketAvatar(raw.fullName, jerseyStr, idx + 1);

    // Match in official Season-2 roster/picks
    const pickAssignment = season2PicksOrder.find(
      (item) => item.fullName.toLowerCase() === raw.fullName.toLowerCase()
    );

    const isCaptain = !!pickAssignment?.isCaptain || teams.some((t) => t.captainPlayerId === playerId);
    const badge: PlayerBadge = isCaptain ? 'CAPTAIN' : (raw.badge || 'ALL-ROUNDER');

    return {
      id: playerId,
      draftId,
      fullName: raw.fullName,
      jerseyNumber: jerseyStr,
      primaryCategoryId: raw.cat,
      playerType: `${raw.bat} • ${raw.bowl}`,
      battingStyle: raw.bat,
      bowlingStyle: raw.bowl,
      badge,
      photoUrl: photo,
      inDraftPool: true,
      contactEmail: raw.email,
      notes: `Bangla: ${raw.bengaliName || raw.fullName}${raw.contact ? ` | Phone: ${raw.contact}` : ''}${raw.currentTeam ? ` | Prev: ${raw.currentTeam}` : ''}`,
      status: pickAssignment ? 'drafted' : 'available',
      isCaptain,
      assignedTeamId: pickAssignment?.teamId,
      assignedCategoryId: pickAssignment?.catId || raw.cat,
      createdAt: now,
      updatedAt: now,
    };
  });

  const draftStartTime = now - 60 * 60 * 1000 * 2;
  const picks: PickRecord[] = season2PicksOrder.map((item) => {
    const matchedPlayer = players.find(
      (p) => p.fullName.toLowerCase() === item.fullName.toLowerCase()
    );
    const playerId = matchedPlayer ? matchedPlayer.id : `player-pick-${item.seq}`;

    return {
      id: `pick-s2-${String(item.seq).padStart(2, '0')}`,
      draftId,
      sequence: item.seq,
      playerId,
      teamId: item.teamId,
      categoryId: item.catId,
      createdAt: draftStartTime + item.seq * 90 * 1000,
    };
  });

  const draft: Draft = {
    id: draftId,
    name: 'Brothers Premier League (BPL)',
    season: 'Season-2',
    logoUrl: DEFAULT_BPL_LOGO,
    status: 'completed',
    completedAt: now - 30 * 60 * 1000,
    currentCategoryId: categories[0].id,
    settings: {
      categoryMode: 'category_by_category',
      animationSpeed: 'normal',
      soundEnabled: true,
      celebrationEnabled: true,
      reducedMotion: false,
      autoSave: true,
    },
    createdAt: draftStartTime,
    updatedAt: now,
  };

  return {
    draft,
    categories,
    teams,
    players,
    picks,
  };
}
