import { Category, Draft, Player, Team } from '../types';
import {
  DEFAULT_BPL_LOGO,
  TEAM_DEFAULT_LOGOS,
  generateCricketAvatar,
} from './imageUtils';

export function createSampleDraftData(): {
  draft: Draft;
  categories: Category[];
  teams: Team[];
  players: Player[];
} {
  const draftId = 'bpl-s2-main';
  const now = Date.now();

  const categories: Category[] = [
    {
      id: 'cat-top-order',
      draftId,
      name: 'Top Order Batter',
      color: '#2563EB',
      iconName: 'Zap',
      order: 1,
      active: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'cat-middle-order',
      draftId,
      name: 'Middle Order Batter',
      color: '#0F9CA6',
      iconName: 'Shield',
      order: 2,
      active: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'cat-bat-all',
      draftId,
      name: 'Batting All-Rounder',
      color: '#16A34A',
      iconName: 'Flame',
      order: 3,
      active: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'cat-bowl-all',
      draftId,
      name: 'Bowling All-Rounder',
      color: '#D97706',
      iconName: 'Award',
      order: 4,
      active: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'cat-bowler',
      draftId,
      name: 'Bowler',
      color: '#DC2626',
      iconName: 'Target',
      order: 5,
      active: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'cat-wk-batter',
      draftId,
      name: 'Wicket Keeper Batsman',
      color: '#7C3AED',
      iconName: 'Hand',
      order: 6,
      active: true,
      createdAt: now,
      updatedAt: now,
    },
  ];

  // 6 Teams Quota per team by default for the 6 BPL franchise teams (total 42 slots for 41 players):
  const default6Quotas: Record<string, number> = {
    'cat-top-order': 2,
    'cat-middle-order': 1,
    'cat-bat-all': 3,
    'cat-bowl-all': 1,
    'cat-bowler': 1,
    'cat-wk-batter': 1,
  };

  // The 6 Official Franchise Teams for BPL Season-2
  const teams: Team[] = [
    {
      id: 'team-warriors',
      draftId,
      name: 'Brothers Warriors',
      shortName: 'BW',
      logoUrl: TEAM_DEFAULT_LOGOS['team-warriors'],
      primaryColor: '#16A34A',
      secondaryColor: '#DCFCE7',
      maxPlayers: 7,
      captainPlayerId: 'player-2', // Asif
      captainName: 'Asif',
      quotas: { ...default6Quotas },
      active: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'team-prime',
      draftId,
      name: 'Prime Brothers Cricket XI',
      shortName: 'PBCXI',
      logoUrl: TEAM_DEFAULT_LOGOS['team-prime'],
      primaryColor: '#EA580C',
      secondaryColor: '#FFEDD5',
      maxPlayers: 7,
      captainPlayerId: 'player-1', // Kazi Shahin
      captainName: 'Kazi Shahin',
      quotas: { ...default6Quotas },
      active: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'team-kings',
      draftId,
      name: 'The Crown Kings',
      shortName: 'TCK',
      logoUrl: TEAM_DEFAULT_LOGOS['team-kings'],
      primaryColor: '#EAB308',
      secondaryColor: '#FEF08A',
      maxPlayers: 7,
      captainPlayerId: 'player-5', // Mostafizur
      captainName: 'Mostafizur Rahman',
      quotas: { ...default6Quotas },
      active: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'team-titans',
      draftId,
      name: 'Brothers Titans',
      shortName: 'BT',
      logoUrl: TEAM_DEFAULT_LOGOS['team-titans'],
      primaryColor: '#2563EB',
      secondaryColor: '#DBEAFE',
      maxPlayers: 7,
      quotas: { ...default6Quotas },
      active: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'team-strikers',
      draftId,
      name: 'Brothers Strikers',
      shortName: 'BS',
      logoUrl: TEAM_DEFAULT_LOGOS['team-strikers'],
      primaryColor: '#DC2626',
      secondaryColor: '#FEE2E2',
      maxPlayers: 7,
      quotas: { ...default6Quotas },
      active: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'team-challengers',
      draftId,
      name: 'Brothers Challengers',
      shortName: 'BC',
      logoUrl: TEAM_DEFAULT_LOGOS['team-challengers'],
      primaryColor: '#0D9488',
      secondaryColor: '#CCFBF1',
      maxPlayers: 7,
      quotas: { ...default6Quotas },
      active: true,
      createdAt: now,
      updatedAt: now,
    },
  ];

  // Helper for Google Drive direct photo URLs
  const gDriveImg = (fileId: string) => `https://lh3.googleusercontent.com/d/${fileId}`;

  // 41 Official Registered Players from BPL Season-2 Sheet
  const officialPlayersRaw = [
    {
      fullName: 'Kazi Shahin',
      email: 'kazishahin511@gmail.com',
      contact: '01303768427',
      cat: 'cat-bat-all',
      bat: 'Right Handed' as const,
      bowl: 'Right Arm Medium',
      currentTeam: 'The Crown Kings',
      badge: 'ALL-ROUNDER' as const,
      driveId: '1cecWfr-TIMYwQ4lwQWSWVQoOldvdvf7t',
    },
    {
      fullName: 'MD NAIEEM KHAN RONI',
      email: 'naiemroni1995@gmail.com',
      contact: '01624285175',
      cat: 'cat-top-order',
      bat: 'Right Handed' as const,
      bowl: 'Right Arm Medium',
      currentTeam: 'Brothers Warriors',
      badge: 'HARD HITTER' as const,
      driveId: '1AgBp6s_tJGTUGFmco5AlW_6cycAc6KnQ',
    },
    {
      fullName: 'Zoni Ahmed',
      email: 'zoniahmed15@gmail.com',
      contact: '01833-081331',
      cat: 'cat-top-order',
      bat: 'Right Handed' as const,
      bowl: 'Right Arm Fast',
      currentTeam: 'Prime Brothers Cricket XI',
      badge: 'GAME CHANGER' as const,
      driveId: '1mkIXYh7Pq5qPxs5-y_8FfpeqdsZlAHOP',
    },
    {
      fullName: 'HK RONY',
      email: 'hkrony62@gmail.com',
      contact: '01613049526',
      cat: 'cat-bat-all',
      bat: 'Right Handed' as const,
      bowl: 'Right Arm Medium',
      currentTeam: 'Prime Brothers Cricket XI',
      badge: 'ALL-ROUNDER' as const,
      driveId: '1qMrXJGidUBuw6YgHtxvIANLPCc5dELhd',
    },
    {
      fullName: 'Mohammad Nazim',
      email: 'theking187049@gmail.com',
      contact: '01797591183',
      cat: 'cat-middle-order',
      bat: 'Right Handed' as const,
      bowl: 'None',
      currentTeam: 'Brothers Warriors',
      badge: 'FINISHER' as const,
      driveId: '1XQ0GYCIRvmMWxdn8bxnnTD6TY8stwl6R',
    },
    {
      fullName: 'Md. Mostafizur Rahman',
      email: 'smrocky176@gmail.com',
      contact: '01618214165',
      cat: 'cat-bowl-all',
      bat: 'Right Handed' as const,
      bowl: 'Right Arm Medium',
      currentTeam: 'Brothers Warriors',
      badge: 'DESTROYER' as const,
      driveId: '1RMBb60fpqWvOq9uXXe_riBtN_qT-878e',
    },
    {
      fullName: 'Selim Badsha',
      email: 'selimbadsha@gmail.com',
      contact: '01893249247',
      cat: 'cat-middle-order',
      bat: 'Right Handed' as const,
      bowl: 'None',
      currentTeam: 'Brothers Warriors',
      badge: 'LEADER' as const,
      driveId: '14RQjdJyRFc1nzWwf_7JS--Jod8Pr7wll',
    },
    {
      fullName: 'Asif',
      email: 'asif.bpl@gmail.com',
      contact: '01623992742',
      cat: 'cat-bowler',
      bat: 'Right Handed' as const,
      bowl: 'Right Arm Fast',
      currentTeam: 'Brothers Warriors',
      badge: 'WICKET TAKER' as const,
      driveId: '1ib3APQq_M9FwAjAiXUIFJES8M_R6hoFd',
    },
    {
      fullName: 'M. Fahim',
      email: 'fahim.bpl@gmail.com',
      contact: '01619416644',
      cat: 'cat-bowl-all',
      bat: 'Right Handed' as const,
      bowl: 'Right Arm Fast',
      currentTeam: 'The Crown Kings',
      badge: 'WICKET TAKER' as const,
      driveId: '13JzBDxajVFjNJKPU4-JJoZsFXAuolIiN',
    },
    {
      fullName: 'MD. Saidul Islam Polash',
      email: 'S.polash120@gmail.com',
      contact: '01972591997',
      cat: 'cat-wk-batter',
      bat: 'Right Handed' as const,
      bowl: 'Right Arm Medium',
      currentTeam: 'Prime Brothers Cricket XI',
      badge: 'SAFE HANDS' as const,
      driveId: '10zvQ-GnfvQVntYdUJhbWrOsSvtIyrOq8',
    },
    {
      fullName: 'Shahriar Alom Rafin',
      email: 'rafinff262@gmail.com',
      contact: '01761148580',
      cat: 'cat-middle-order',
      bat: 'Right Handed' as const,
      bowl: 'None',
      currentTeam: 'Prime Brothers Cricket XI',
      badge: 'FINISHER' as const,
      driveId: '1MJXgaleOYS7Nzx41bl8gGpo0Z8vPwydr',
    },
    {
      fullName: 'Tusher Hossain',
      email: 'tusher.bpl@gmail.com',
      contact: '01855490339',
      cat: 'cat-bat-all',
      bat: 'Right Handed' as const,
      bowl: 'Right Arm Medium',
      currentTeam: 'Brothers Warriors',
      badge: 'ALL-ROUNDER' as const,
      driveId: '1JMaNSfa2W_k-zauo1ye5eijF6IIJtE5z',
    },
    {
      fullName: 'Jahangir',
      email: 'ja9771765@gmail.com',
      contact: '01609757285',
      cat: 'cat-bat-all',
      bat: 'Right Handed' as const,
      bowl: 'Right Arm Medium',
      currentTeam: 'Prime Brothers Cricket XI',
      badge: 'ALL-ROUNDER' as const,
      driveId: '1HKb3BnXcD6xF3R1Khv9C6y5ConN9vQr9',
    },
    {
      fullName: 'Mehedi Hasan Mithun',
      email: 'mehedihasan20333@gmail.com',
      contact: '01882670212',
      cat: 'cat-bat-all',
      bat: 'Right Handed' as const,
      bowl: 'Right Arm Medium',
      currentTeam: 'Brothers Warriors',
      badge: 'ALL-ROUNDER' as const,
      driveId: '1KTaY5hLg06GSUa_PqndXPn5lErlMJvO9',
    },
    {
      fullName: 'Sakhawat Hossain',
      email: 'sakhawat.bpl@gmail.com',
      contact: '01601998679',
      cat: 'cat-top-order',
      bat: 'Right Handed' as const,
      bowl: 'None',
      currentTeam: 'Prime Brothers Cricket XI',
      badge: 'CLASSIC' as const,
      driveId: '1Js_uHDc4geX_u0o_BhiliP0vLfm4ihP',
    },
    {
      fullName: 'Monjurul Islam',
      email: 'monjurulcakari@gmail.com',
      contact: '01776651356',
      cat: 'cat-bat-all',
      bat: 'Right Handed' as const,
      bowl: 'Right Arm Fast',
      currentTeam: 'Prime Brothers Cricket XI',
      badge: 'ALL-ROUNDER' as const,
      driveId: '1A9ryMX8z2QCp_OnG5y8wRvnP-wO5ATFJ',
    },
    {
      fullName: 'Abdullah Akash',
      email: 'akash.bpl@gmail.com',
      contact: '01856677832',
      cat: 'cat-wk-batter',
      bat: 'Right Handed' as const,
      bowl: 'None',
      currentTeam: 'The Crown Kings',
      badge: 'SAFE HANDS' as const,
      driveId: '1MPM0tiBZtp0AmiN-itFYFVH3mXdQYb9o',
    },
    {
      fullName: 'Abdullah Al Mamun',
      email: 'mamun.bpl@gmail.com',
      contact: '01815892290',
      cat: 'cat-bat-all',
      bat: 'Right Handed' as const,
      bowl: 'Right Arm Medium',
      currentTeam: 'The Crown Kings',
      badge: 'ALL-ROUNDER' as const,
      driveId: '1m4N_j9MPlfV6KclND6gz5LyFmUWIjdj7',
    },
    {
      fullName: 'Y.A. Jony',
      email: 'ya.jony@gmail.com',
      contact: '01934594920',
      cat: 'cat-bat-all',
      bat: 'Right Handed' as const,
      bowl: 'Right Arm Medium',
      currentTeam: 'Prime Brothers Cricket XI',
      badge: 'ALL-ROUNDER' as const,
      driveId: '1w7u4bM1H6XVI83z4v0qWu0redwRDnlS8',
    },
    {
      fullName: 'Ashik Mahmud',
      email: 'ashik.bpl@gmail.com',
      contact: '01706939151',
      cat: 'cat-bat-all',
      bat: 'Right Handed' as const,
      bowl: 'Right Arm Medium',
      currentTeam: 'Brothers Warriors',
      badge: 'ALL-ROUNDER' as const,
      driveId: '1tgc2T7cdkIQ7oocLeOLexV1wW6DB_C96',
    },
    {
      fullName: 'Sohrab Ahmed Ayan',
      email: 'sohrab.bpl@gmail.com',
      contact: '01607126226',
      cat: 'cat-bat-all',
      bat: 'Right Handed' as const,
      bowl: 'Right Arm Fast',
      currentTeam: 'Brothers Warriors',
      badge: 'HARD HITTER' as const,
      driveId: '1cvUjrQDOuYJhQRiaMW90jy4DNgZrceeJ',
    },
    {
      fullName: 'FH Noman',
      email: 'mdnomanahmed16@gmail.com',
      contact: '01857697069',
      cat: 'cat-bowl-all',
      bat: 'Right Handed' as const,
      bowl: 'Right Arm Fast',
      currentTeam: 'The Crown Kings',
      badge: 'WICKET TAKER' as const,
      driveId: '19IZKmuyBlfmeOL1Iu_UaZ56-3mTp7Iyt',
    },
    {
      fullName: 'Rana',
      email: 'rana.bpl@gmail.com',
      contact: '01810760541',
      cat: 'cat-top-order',
      bat: 'Right Handed' as const,
      bowl: 'None',
      currentTeam: 'Brothers Warriors',
      badge: 'HARD HITTER' as const,
      driveId: '1RAjVOWfPnr_6M8rBfI7fxcaAvsaVWGcU',
    },
    {
      fullName: 'Omar Hossain',
      email: 'omar.bpl@gmail.com',
      contact: '01633522580',
      cat: 'cat-top-order',
      bat: 'Right Handed' as const,
      bowl: 'Right Arm Medium',
      currentTeam: 'Prime Brothers Cricket XI',
      badge: 'CLASSIC' as const,
      driveId: '1UbezOj9-WOHL_yY1Q95lRkjqPO3lqmrL',
    },
    {
      fullName: 'Saiful Islam Antor',
      email: 'Antorn19@gmail.com',
      contact: '01944009577',
      cat: 'cat-middle-order',
      bat: 'Right Handed' as const,
      bowl: 'None',
      currentTeam: 'The Crown Kings',
      badge: 'FINISHER' as const,
      driveId: '1YDfFpwYX26tVPWfnlurqBvf5EBRTt7UJ',
    },
    {
      fullName: 'Rezvi',
      email: 'greenglow214@gmail.com',
      contact: '01791168132',
      cat: 'cat-bat-all',
      bat: 'Right Handed' as const,
      bowl: 'Right Arm Medium',
      currentTeam: 'Prime Brothers Cricket XI',
      badge: 'ALL-ROUNDER' as const,
      driveId: '1ORK70NaWvB6k--fHSTc2IsS3HYNEC_4B',
    },
    {
      fullName: 'RA Apon',
      email: 'apon06canva@gmail.com',
      contact: '01816462090',
      cat: 'cat-bat-all',
      bat: 'Right Handed' as const,
      bowl: 'Right Arm Medium',
      currentTeam: 'The Crown Kings',
      badge: 'GAME CHANGER' as const,
      driveId: '1L3FV6OQEIazz1beEm0THSUSM2WCiHJa7',
    },
    {
      fullName: 'Shafiqul Islam',
      email: 'shafiquldesigner57@gmail.com',
      contact: '01942068764',
      cat: 'cat-bat-all',
      bat: 'Right Handed' as const,
      bowl: 'Right Arm Medium',
      currentTeam: 'Brothers Warriors',
      badge: 'ALL-ROUNDER' as const,
      driveId: '1OkTbsfwNnfunsUOl68tGCl-YKYtwtcPs',
    },
    {
      fullName: 'Md. Sohanur Rohman',
      email: 'sohanur.bpl@gmail.com',
      contact: '01781292912',
      cat: 'cat-wk-batter',
      bat: 'Right Handed' as const,
      bowl: 'Left Arm Spinner',
      currentTeam: 'The Crown Kings',
      badge: 'SAFE HANDS' as const,
      driveId: '15iAEG1x0dkH1Jj7ebtADIf5V7Epcb3ec',
    },
    {
      fullName: 'Shuvo',
      email: 'shuvo.bpl@gmail.com',
      contact: '01829548006',
      cat: 'cat-wk-batter',
      bat: 'Right Handed' as const,
      bowl: 'None',
      currentTeam: 'The Crown Kings',
      badge: 'SAFE HANDS' as const,
      driveId: '1GtqK9-oJXLFDlTx3HXjzO78iFdAOhw12',
    },
    {
      fullName: 'RS Rafiq',
      email: 'rsboy8437@gmail.com',
      contact: '01679531737',
      cat: 'cat-bat-all',
      bat: 'Right Handed' as const,
      bowl: 'Right Arm Medium',
      currentTeam: 'Brothers Warriors',
      badge: 'ALL-ROUNDER' as const,
      driveId: '16DNMC7FhULPd6dKbpJVtAnaycAHjr-Rq',
    },
    {
      fullName: 'Shamim Islam',
      email: 'shamim.bpl@gmail.com',
      contact: '01904174565',
      cat: 'cat-bowl-all',
      bat: 'Right Handed' as const,
      bowl: 'Right Arm Fast',
      currentTeam: 'Brothers Warriors',
      badge: 'WICKET TAKER' as const,
      driveId: '1mVq2nz1fCRo5MlpwZlEYMwabLWkAuMR8',
    },
    {
      fullName: 'Arif Iquebal',
      email: 'arif.bpl@gmail.com',
      contact: '01878113798',
      cat: 'cat-bat-all',
      bat: 'Right Handed' as const,
      bowl: 'Right Arm Medium',
      currentTeam: 'Brothers Warriors',
      badge: 'GAME CHANGER' as const,
      driveId: '1Qigba-LT2bTDAGLw9Iozc785a4-PUPDv',
    },
    {
      fullName: 'Ashraful Shohel',
      email: 'westernmuslimabad@gmail.com',
      contact: 'westernmuslimabad@gmail.com',
      cat: 'cat-wk-batter',
      bat: 'Left Handed' as const,
      bowl: 'Left Arm Medium',
      currentTeam: 'Brothers Warriors',
      badge: 'SAFE HANDS' as const,
      driveId: '1D_yJhVBeGbpe2YxnoceYzMoRQ-7suTME',
    },
    {
      fullName: 'AR Mukul',
      email: 'ar.mukul@gmail.com',
      contact: '01673640084',
      cat: 'cat-bat-all',
      bat: 'Right Handed' as const,
      bowl: 'Right Arm Medium',
      currentTeam: 'Brothers Warriors',
      badge: 'LEADER' as const,
      driveId: '1ObOKZ9dU7teNp_x5purMBThWxZZZc-0Q',
    },
    {
      fullName: 'Roni Khan',
      email: 'ronikhan.bpl@gmail.com',
      contact: '01753146250',
      cat: 'cat-bat-all',
      bat: 'Right Handed' as const,
      bowl: 'Right Arm Fast',
      currentTeam: 'Brothers Warriors',
      badge: 'HARD HITTER' as const,
      driveId: '1L707lXwXWm0coC9RWYEWfb54qz0abm6A',
    },
    {
      fullName: 'Rana Khan',
      email: 'ranakhan.bpl@gmail.com',
      contact: '01538370725',
      cat: 'cat-top-order',
      bat: 'Right Handed' as const,
      bowl: 'Right Arm Fast',
      currentTeam: 'Prime Brothers Cricket XI',
      badge: 'HARD HITTER' as const,
      driveId: '1W6O9tDr3Ozonw37WmQ0NbSxM7UMNe2wD',
    },
    {
      fullName: 'M Saiful',
      email: 'saiful.bpl@gmail.com',
      contact: '01740705002',
      cat: 'cat-bowler',
      bat: 'Right Handed' as const,
      bowl: 'Right Arm Fast',
      currentTeam: 'The Crown Kings',
      badge: 'WICKET TAKER' as const,
      driveId: '1gSX5kQvd_gEsPFW2SJ0NLhflLvCH5dJi',
    },
    {
      fullName: 'Mohammad Emon',
      email: 'tee279783@gmail.com',
      contact: '01516596165',
      cat: 'cat-top-order',
      bat: 'Right Handed' as const,
      bowl: 'None',
      currentTeam: 'The Crown Kings',
      badge: 'CLASSIC' as const,
      driveId: '1HeTukSsjBmq68yjDQZOS3PtM7ivZwFj9',
    },
    {
      fullName: 'MD Mokka Sarker',
      email: 'mokka.bpl@gmail.com',
      contact: '01793626848',
      cat: 'cat-top-order',
      bat: 'Right Handed' as const,
      bowl: 'None',
      currentTeam: 'The Crown Kings',
      badge: 'GAME CHANGER' as const,
      driveId: '1ln3WKnE0o4c2CSA3707Cg-IoZpFmH5hR',
    },
    {
      fullName: 'LKD Sadek',
      email: 'sadek.bpl@gmail.com',
      contact: '01407656394',
      cat: 'cat-bowl-all',
      bat: 'Right Handed' as const,
      bowl: 'Right Arm Medium',
      currentTeam: 'Brothers Warriors',
      badge: 'DESTROYER' as const,
      driveId: '109FYXUU8aXVClrxt5q4ayfD4tGenDcTS',
    },
  ];

  const players: Player[] = officialPlayersRaw.map((raw, idx) => {
    const jerseyStr = String(idx + 1).padStart(2, '0');
    const playerId = `player-${idx + 1}`;
    const catObj = categories.find((c) => c.id === raw.cat);
    const catName = catObj ? catObj.name : 'All-Rounder';
    const photo = raw.driveId ? gDriveImg(raw.driveId) : generateCricketAvatar(raw.fullName, jerseyStr, idx + 1);

    // Check if player is a pre-selected captain of any franchise team
    const teamWithCaptain = teams.find(
      (t) => t.captainPlayerId === playerId || (t.captainName && t.captainName.toLowerCase() === raw.fullName.toLowerCase())
    );
    const isCaptain = !!teamWithCaptain;

    return {
      id: playerId,
      draftId,
      fullName: raw.fullName,
      jerseyNumber: jerseyStr,
      primaryCategoryId: raw.cat,
      playerType: `${raw.bat} • ${raw.bowl}`,
      battingStyle: raw.bat,
      bowlingStyle: raw.bowl,
      badge: isCaptain ? 'CAPTAIN' : raw.badge,
      photoUrl: photo,
      inDraftPool: true,
      contactEmail: raw.email,
      notes: `Contact: ${raw.contact} | Original Team: ${raw.currentTeam}`,
      status: isCaptain ? 'drafted' : 'available',
      isCaptain,
      assignedTeamId: teamWithCaptain ? teamWithCaptain.id : undefined,
      assignedCategoryId: isCaptain ? raw.cat : undefined,
      createdAt: now,
      updatedAt: now,
    };
  });

  const draft: Draft = {
    id: draftId,
    name: 'Brothers Premier League (BPL)',
    season: 'Season-2',
    logoUrl: DEFAULT_BPL_LOGO,
    status: 'live',
    currentCategoryId: categories[0].id,
    settings: {
      categoryMode: 'category_by_category',
      animationSpeed: 'normal',
      soundEnabled: true,
      celebrationEnabled: true,
      reducedMotion: false,
      autoSave: true,
    },
    createdAt: now,
    updatedAt: now,
  };

  return {
    draft,
    categories,
    teams,
    players,
  };
}
