import { Category, Draft, Player, PlayerBadge, Team } from '../types';
import {
  DEFAULT_BPL_LOGO,
  TEAM_DEFAULT_LOGOS,
  generateCricketAvatar,
} from './imageUtils';

export function createSampleDraftData(): {
  draft: Draft;
  categories: Category[];
  teams: Team[];
  players: Player[];
} {
  const draftId = 'bpl-s2-main';
  const now = Date.now();

  // 10 Official Categories matching the Tournament Photo with English Names
  const categories: Category[] = [
    {
      id: 'cat-bat-lvl-1',
      draftId,
      name: 'Batsman Level-01',
      color: '#2563EB',
      iconName: 'Zap',
      order: 1,
      active: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'cat-bat-lvl-2',
      draftId,
      name: 'Batsman Level-02',
      color: '#0284C7',
      iconName: 'Shield',
      order: 2,
      active: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'cat-bat-lvl-3',
      draftId,
      name: 'Batsman Level-03',
      color: '#0D9488',
      iconName: 'Flame',
      order: 3,
      active: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'cat-bat-lvl-4',
      draftId,
      name: 'Batsman Level-04',
      color: '#059669',
      iconName: 'Award',
      order: 4,
      active: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'cat-bowl-bat-equal',
      draftId,
      name: 'Bowling-Batting Equal',
      color: '#D97706',
      iconName: 'Scale',
      order: 5,
      active: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'cat-bat-all-round',
      draftId,
      name: 'Batting All-Rounder',
      color: '#EA580C',
      iconName: 'Flame',
      order: 6,
      active: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'cat-slow-bowl-all',
      draftId,
      name: 'Slow Bowling All-Rounder',
      color: '#7C3AED',
      iconName: 'RotateCw',
      order: 7,
      active: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'cat-bat-all-lvl-2',
      draftId,
      name: 'Batting All-Rounder Level-2',
      color: '#C026D3',
      iconName: 'Sparkles',
      order: 8,
      active: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'cat-bowling',
      draftId,
      name: 'Bowling',
      color: '#DC2626',
      iconName: 'Target',
      order: 9,
      active: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'cat-mini-all',
      draftId,
      name: 'Mini All-Rounder',
      color: '#4F46E5',
      iconName: 'Users',
      order: 10,
      active: true,
      createdAt: now,
      updatedAt: now,
    },
  ];

  // 6 Teams Quota: 1 per category (10 categories = 10 picks + 1 captain = 11 players per team)
  const default6Quotas: Record<string, number> = {
    'cat-bat-lvl-1': 1,
    'cat-bat-lvl-2': 1,
    'cat-bat-lvl-3': 1,
    'cat-bat-lvl-4': 1,
    'cat-bowl-bat-equal': 1,
    'cat-bat-all-round': 1,
    'cat-slow-bowl-all': 1,
    'cat-bat-all-lvl-2': 1,
    'cat-bowling': 1,
    'cat-mini-all': 1,
  };

  // The 6 Official Franchise Teams for BPL Season-2
  const teams: Team[] = [
    {
      id: 'team-warriors',
      draftId,
      name: 'Brothers Warriors',
      shortName: 'BW',
      logoUrl: TEAM_DEFAULT_LOGOS['team-warriors'],
      primaryColor: '#16A34A',
      secondaryColor: '#DCFCE7',
      maxPlayers: 11,
      captainPlayerId: 'player-asif',
      captainName: 'Asif',
      quotas: { ...default6Quotas },
      active: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'team-prime',
      draftId,
      name: 'Prime Brothers Cricket XI',
      shortName: 'PBCXI',
      logoUrl: TEAM_DEFAULT_LOGOS['team-prime'],
      primaryColor: '#EA580C',
      secondaryColor: '#FFEDD5',
      maxPlayers: 11,
      captainPlayerId: 'player-shahin',
      captainName: 'Kazi Shahin',
      quotas: { ...default6Quotas },
      active: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'team-kings',
      draftId,
      name: 'The Crown Kings',
      shortName: 'TCK',
      logoUrl: TEAM_DEFAULT_LOGOS['team-kings'],
      primaryColor: '#EAB308',
      secondaryColor: '#FEF08A',
      maxPlayers: 11,
      captainPlayerId: 'player-mostafiz',
      captainName: 'Md. Mostafizur Rahman',
      quotas: { ...default6Quotas },
      active: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'team-titans',
      draftId,
      name: 'Brothers Titans',
      shortName: 'BT',
      logoUrl: TEAM_DEFAULT_LOGOS['team-titans'],
      primaryColor: '#2563EB',
      secondaryColor: '#DBEAFE',
      maxPlayers: 11,
      quotas: { ...default6Quotas },
      active: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'team-strikers',
      draftId,
      name: 'Brothers Strikers',
      shortName: 'BS',
      logoUrl: TEAM_DEFAULT_LOGOS['team-strikers'],
      primaryColor: '#DC2626',
      secondaryColor: '#FEE2E2',
      maxPlayers: 11,
      quotas: { ...default6Quotas },
      active: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'team-challengers',
      draftId,
      name: 'Brothers Challengers',
      shortName: 'BC',
      logoUrl: TEAM_DEFAULT_LOGOS['team-challengers'],
      primaryColor: '#0D9488',
      secondaryColor: '#CCFBF1',
      maxPlayers: 11,
      quotas: { ...default6Quotas },
      active: true,
      createdAt: now,
      updatedAt: now,
    },
  ];

  // Helper for Google Drive direct photo URLs
  const gDriveImg = (fileId: string) => `https://lh3.googleusercontent.com/d/${fileId}`;

  // Complete Roster: All 60 Players from the Photo + Registered Franchise Captains
  // Category IDs match the 10 Categories exactly
  const officialPlayersRaw: Array<{
    idKey?: string;
    fullName: string;
    bengaliName?: string;
    email?: string;
    contact?: string;
    cat: string;
    bat: 'Right Handed' | 'Left Handed';
    bowl: string;
    currentTeam?: string;
    badge: PlayerBadge;
    driveId?: string;
  }> = [
    // =========================================================================
    // SECTION 1: BATSMAN CATEGORY (ব্যাটসম্যান ক্যাটাগরি)
    // =========================================================================

    // --- Batsman Level-01 (ব্যাটসম্যান লেভেল-০১) ---
    {
      fullName: 'Abdullah Akash',
      bengaliName: 'আকাশ',
      email: 'akash.bpl@gmail.com',
      contact: '01856677832',
      cat: 'cat-bat-lvl-1',
      bat: 'Right Handed',
      bowl: 'None',
      currentTeam: 'The Crown Kings',
      badge: 'SAFE HANDS',
      driveId: '1MPM0tiBZtp0AmiN-itFYFVH3mXdQYb9o',
    },
    {
      fullName: 'Mohammad Emon',
      bengaliName: 'ইমন',
      email: 'tee279783@gmail.com',
      contact: '01516596165',
      cat: 'cat-bat-lvl-1',
      bat: 'Right Handed',
      bowl: 'None',
      currentTeam: 'The Crown Kings',
      badge: 'CLASSIC',
      driveId: '1HeTukSsjBmq68yjDQZOS3PtM7ivZwFj9',
    },
    {
      fullName: 'Rayhan Emon',
      bengaliName: 'রায়হান ইমন',
      cat: 'cat-bat-lvl-1',
      bat: 'Right Handed',
      bowl: 'Left Arm Spinner',
      badge: 'HARD HITTER',
    },
    {
      fullName: 'Jahangir',
      bengaliName: 'জাহাঙ্গীর',
      email: 'ja9771765@gmail.com',
      contact: '01609757285',
      cat: 'cat-bat-lvl-1',
      bat: 'Right Handed',
      bowl: 'Right Arm Medium',
      currentTeam: 'Prime Brothers Cricket XI',
      badge: 'ALL-ROUNDER',
      driveId: '1HKb3BnXcD6xF3R1Khv9C6y5ConN9vQr9',
    },
    {
      fullName: 'MD. Saidul Islam Polash',
      bengaliName: 'পলাশ',
      email: 'S.polash120@gmail.com',
      contact: '01972591997',
      cat: 'cat-bat-lvl-1',
      bat: 'Right Handed',
      bowl: 'Right Arm Medium',
      currentTeam: 'Prime Brothers Cricket XI',
      badge: 'SAFE HANDS',
      driveId: '10zvQ-GnfvQVntYdUJhbWrOsSvtIyrOq8',
    },
    {
      fullName: 'Mohon',
      bengaliName: 'মোহন',
      cat: 'cat-bat-lvl-1',
      bat: 'Right Handed',
      bowl: 'None',
      badge: 'CLASSIC',
    },

    // --- Batsman Level-02 (ব্যাটসম্যান লেভেল-০২) ---
    {
      fullName: 'Abran',
      bengaliName: 'আবরান',
      cat: 'cat-bat-lvl-2',
      bat: 'Right Handed',
      bowl: 'Right Arm Medium',
      badge: 'HARD HITTER',
    },
    {
      fullName: 'Sakhawat Hossain',
      bengaliName: 'শাখাওয়াত',
      email: 'sakhawat.bpl@gmail.com',
      contact: '01601998679',
      cat: 'cat-bat-lvl-2',
      bat: 'Right Handed',
      bowl: 'None',
      currentTeam: 'Prime Brothers Cricket XI',
      badge: 'CLASSIC',
      driveId: '1Js_uHDc4geX_u0o_BhiliP0vLfm4ihP',
    },
    {
      fullName: 'MD NAIEEM KHAN RONI',
      bengaliName: 'নাঈম রনি',
      email: 'naiemroni1995@gmail.com',
      contact: '01624285175',
      cat: 'cat-bat-lvl-2',
      bat: 'Right Handed',
      bowl: 'Right Arm Medium',
      currentTeam: 'Brothers Warriors',
      badge: 'HARD HITTER',
      driveId: '1AgBp6s_tJGTUGFmco5AlW_6cycAc6KnQ',
    },
    {
      fullName: 'Omar Hossain',
      bengaliName: 'ওমর',
      email: 'omar.bpl@gmail.com',
      contact: '01633522580',
      cat: 'cat-bat-lvl-2',
      bat: 'Right Handed',
      bowl: 'Right Arm Medium',
      currentTeam: 'Prime Brothers Cricket XI',
      badge: 'CLASSIC',
      driveId: '1UbezOj9-WOHL_yY1Q95lRkjqPO3lqmrL',
    },
    {
      fullName: 'Saiful Islam Antor',
      bengaliName: 'অন্তর',
      email: 'Antorn19@gmail.com',
      contact: '01944009577',
      cat: 'cat-bat-lvl-2',
      bat: 'Right Handed',
      bowl: 'None',
      currentTeam: 'The Crown Kings',
      badge: 'FINISHER',
      driveId: '1YDfFpwYX26tVPWfnlurqBvf5EBRTt7UJ',
    },
    {
      fullName: 'Shuvo',
      bengaliName: 'শুভ',
      email: 'shuvo.bpl@gmail.com',
      contact: '01829548006',
      cat: 'cat-bat-lvl-2',
      bat: 'Right Handed',
      bowl: 'None',
      currentTeam: 'The Crown Kings',
      badge: 'SAFE HANDS',
      driveId: '1GtqK9-oJXLFDlTx3HXjzO78iFdAOhw12',
    },

    // --- Batsman Level-03 (ব্যাটসম্যান লেভেল-০৩) ---
    {
      fullName: 'MD Mokka Sarker',
      bengaliName: 'মক্কা',
      email: 'mokka.bpl@gmail.com',
      contact: '01793626848',
      cat: 'cat-bat-lvl-3',
      bat: 'Right Handed',
      bowl: 'None',
      currentTeam: 'The Crown Kings',
      badge: 'GAME CHANGER',
      driveId: '1ln3WKnE0o4c2CSA3707Cg-IoZpFmH5hR',
    },
    {
      fullName: 'Shuvo Senior',
      bengaliName: 'শুভ সিনিয়র',
      cat: 'cat-bat-lvl-3',
      bat: 'Right Handed',
      bowl: 'Right Arm Medium',
      badge: 'LEADER',
    },
    {
      fullName: 'Rana Khan',
      bengaliName: 'রানা খান',
      email: 'ranakhan.bpl@gmail.com',
      contact: '01538370725',
      cat: 'cat-bat-lvl-3',
      bat: 'Right Handed',
      bowl: 'Right Arm Fast',
      currentTeam: 'Prime Brothers Cricket XI',
      badge: 'HARD HITTER',
      driveId: '1W6O9tDr3Ozonw37WmQ0NbSxM7UMNe2wD',
    },
    {
      fullName: 'Ashraful Shohel',
      bengaliName: 'আশরাফুল',
      email: 'westernmuslimabad@gmail.com',
      contact: '01833000000',
      cat: 'cat-bat-lvl-3',
      bat: 'Left Handed',
      bowl: 'Left Arm Medium',
      currentTeam: 'Brothers Warriors',
      badge: 'SAFE HANDS',
      driveId: '1D_yJhVBeGbpe2YxnoceYzMoRQ-7suTME',
    },
    {
      fullName: 'Arif Khan',
      bengaliName: 'আরিফ খান',
      cat: 'cat-bat-lvl-3',
      bat: 'Right Handed',
      bowl: 'Right Arm Medium',
      badge: 'CLASSIC',
    },
    {
      fullName: 'Zahid',
      bengaliName: 'জাহিদ',
      cat: 'cat-bat-lvl-3',
      bat: 'Right Handed',
      bowl: 'Right Arm Medium',
      badge: 'HARD HITTER',
    },

    // --- Batsman Level-04 (ব্যাটসম্যান লেভেল-০৪) ---
    {
      fullName: 'Shahriar Alom Rafin',
      bengaliName: 'শাহরিয়ার',
      email: 'rafinff262@gmail.com',
      contact: '01761148580',
      cat: 'cat-bat-lvl-4',
      bat: 'Right Handed',
      bowl: 'None',
      currentTeam: 'Prime Brothers Cricket XI',
      badge: 'FINISHER',
      driveId: '1MJXgaleOYS7Nzx41bl8gGpo0Z8vPwydr',
    },
    {
      fullName: 'Alauddin',
      bengaliName: 'আলাউদ্দিন',
      cat: 'cat-bat-lvl-4',
      bat: 'Right Handed',
      bowl: 'Right Arm Medium',
      badge: 'CLASSIC',
    },
    {
      fullName: 'Alal',
      bengaliName: 'আলাল',
      cat: 'cat-bat-lvl-4',
      bat: 'Right Handed',
      bowl: 'Right Arm Medium',
      badge: 'HARD HITTER',
    },
    {
      fullName: 'Md. Sohanur Rohman',
      bengaliName: 'সোহান',
      email: 'sohanur.bpl@gmail.com',
      contact: '01781292912',
      cat: 'cat-bat-lvl-4',
      bat: 'Right Handed',
      bowl: 'Left Arm Spinner',
      currentTeam: 'The Crown Kings',
      badge: 'SAFE HANDS',
      driveId: '15iAEG1x0dkH1Jj7ebtADIf5V7Epcb3ec',
    },
    {
      fullName: 'Selim Badsha',
      bengaliName: 'সেলিম',
      email: 'selimbadsha@gmail.com',
      contact: '01893249247',
      cat: 'cat-bat-lvl-4',
      bat: 'Right Handed',
      bowl: 'None',
      currentTeam: 'Brothers Warriors',
      badge: 'LEADER',
      driveId: '14RQjdJyRFc1nzWwf_7JS--Jod8Pr7wll',
    },
    {
      fullName: 'Rana',
      bengaliName: 'রানা',
      email: 'rana.bpl@gmail.com',
      contact: '01810760541',
      cat: 'cat-bat-lvl-4',
      bat: 'Right Handed',
      bowl: 'None',
      currentTeam: 'Brothers Warriors',
      badge: 'HARD HITTER',
      driveId: '1RAjVOWfPnr_6M8rBfI7fxcaAvsaVWGcU',
    },

    // =========================================================================
    // SECTION 2: ALL-ROUNDER CATEGORY (অলরাউন্ডার ক্যাটাগরি)
    // =========================================================================

    // --- Bowling-Batting Equal (বোলিং-ব্যাটিং সমান) ---
    {
      fullName: 'M. Fahim',
      bengaliName: 'ফাহিম',
      email: 'fahim.bpl@gmail.com',
      contact: '01619416644',
      cat: 'cat-bowl-bat-equal',
      bat: 'Right Handed',
      bowl: 'Right Arm Fast',
      currentTeam: 'The Crown Kings',
      badge: 'WICKET TAKER',
      driveId: '13JzBDxajVFjNJKPU4-JJoZsFXAuolIiN',
    },
    {
      fullName: 'Khalek',
      bengaliName: 'খালেক',
      cat: 'cat-bowl-bat-equal',
      bat: 'Right Handed',
      bowl: 'Right Arm Fast',
      badge: 'ALL-ROUNDER',
    },
    {
      fullName: 'Sohrab Ahmed Ayan',
      bengaliName: 'অয়ন',
      email: 'sohrab.bpl@gmail.com',
      contact: '01607126226',
      cat: 'cat-bowl-bat-equal',
      bat: 'Right Handed',
      bowl: 'Right Arm Fast',
      currentTeam: 'Brothers Warriors',
      badge: 'HARD HITTER',
      driveId: '1cvUjrQDOuYJhQRiaMW90jy4DNgZrceeJ',
    },
    {
      fullName: 'Hasan',
      bengaliName: 'হাসান',
      cat: 'cat-bowl-bat-equal',
      bat: 'Right Handed',
      bowl: 'Right Arm Medium',
      badge: 'ALL-ROUNDER',
    },
    {
      fullName: 'Tanzim',
      bengaliName: 'তানজিম',
      cat: 'cat-bowl-bat-equal',
      bat: 'Right Handed',
      bowl: 'Right Arm Medium',
      badge: 'GAME CHANGER',
    },
    {
      fullName: 'RA Apon',
      bengaliName: 'আপন',
      email: 'apon06canva@gmail.com',
      contact: '01816462090',
      cat: 'cat-bowl-bat-equal',
      bat: 'Right Handed',
      bowl: 'Right Arm Medium',
      currentTeam: 'The Crown Kings',
      badge: 'GAME CHANGER',
      driveId: '1L3FV6OQEIazz1beEm0THSUSM2WCiHJa7',
    },

    // --- Batting All-Rounder (ব্যাটিং অলরাউন্ডার) ---
    {
      fullName: 'AR Mukul',
      bengaliName: 'মুকুল',
      email: 'ar.mukul@gmail.com',
      contact: '01673640084',
      cat: 'cat-bat-all-round',
      bat: 'Right Handed',
      bowl: 'Right Arm Medium',
      currentTeam: 'Brothers Warriors',
      badge: 'LEADER',
      driveId: '1ObOKZ9dU7teNp_x5purMBThWxZZZc-0Q',
    },
    {
      fullName: 'Shafiqul Islam',
      bengaliName: 'শফিক',
      email: 'shafiquldesigner57@gmail.com',
      contact: '01942068764',
      cat: 'cat-bat-all-round',
      bat: 'Right Handed',
      bowl: 'Right Arm Medium',
      currentTeam: 'Brothers Warriors',
      badge: 'ALL-ROUNDER',
      driveId: '1OkTbsfwNnfunsUOl68tGCl-YKYtwtcPs',
    },
    {
      fullName: 'Zoni Ahmed',
      bengaliName: 'জনি-২',
      email: 'zoniahmed15@gmail.com',
      contact: '01833-081331',
      cat: 'cat-bat-all-round',
      bat: 'Right Handed',
      bowl: 'Right Arm Fast',
      currentTeam: 'Prime Brothers Cricket XI',
      badge: 'GAME CHANGER',
      driveId: '1mkIXYh7Pq5qPxs5-y_8FfpeqdsZlAHOP',
    },
    {
      fullName: 'Rezvi',
      bengaliName: 'রেজভি',
      email: 'greenglow214@gmail.com',
      contact: '01791168132',
      cat: 'cat-bat-all-round',
      bat: 'Right Handed',
      bowl: 'Right Arm Medium',
      currentTeam: 'Prime Brothers Cricket XI',
      badge: 'ALL-ROUNDER',
      driveId: '1ORK70NaWvB6k--fHSTc2IsS3HYNEC_4B',
    },
    {
      fullName: 'Mehedi Hasan Mithun',
      bengaliName: 'মিঠুন',
      email: 'mehedihasan20333@gmail.com',
      contact: '01882670212',
      cat: 'cat-bat-all-round',
      bat: 'Right Handed',
      bowl: 'Right Arm Medium',
      currentTeam: 'Brothers Warriors',
      badge: 'ALL-ROUNDER',
      driveId: '1KTaY5hLg06GSUa_PqndXPn5lErlMJvO9',
    },
    {
      fullName: 'Sujan',
      bengaliName: 'সুজন',
      cat: 'cat-bat-all-round',
      bat: 'Right Handed',
      bowl: 'Right Arm Medium',
      badge: 'ALL-ROUNDER',
    },

    // --- Slow Bowling All-Rounder (স্লো বোলিং অলরাউন্ডার) ---
    {
      fullName: 'Arif Iquebal',
      bengaliName: 'আরিফ ইকবাল',
      email: 'arif.bpl@gmail.com',
      contact: '01878113798',
      cat: 'cat-slow-bowl-all',
      bat: 'Right Handed',
      bowl: 'Right Arm Medium',
      currentTeam: 'Brothers Warriors',
      badge: 'GAME CHANGER',
      driveId: '1Qigba-LT2bTDAGLw9Iozc785a4-PUPDv',
    },
    {
      fullName: 'Sohag',
      bengaliName: 'সোহাগ',
      cat: 'cat-slow-bowl-all',
      bat: 'Right Handed',
      bowl: 'Right Arm Off Spin',
      badge: 'ALL-ROUNDER',
    },
    {
      fullName: 'Y.A. Jony',
      bengaliName: 'জনি',
      email: 'ya.jony@gmail.com',
      contact: '01934594920',
      cat: 'cat-slow-bowl-all',
      bat: 'Right Handed',
      bowl: 'Right Arm Medium',
      currentTeam: 'Prime Brothers Cricket XI',
      badge: 'ALL-ROUNDER',
      driveId: '1w7u4bM1H6XVI83z4v0qWu0redwRDnlS8',
    },
    {
      fullName: 'Khorshed',
      bengaliName: 'খোরশেদ',
      cat: 'cat-slow-bowl-all',
      bat: 'Right Handed',
      bowl: 'Right Arm Off Spin',
      badge: 'ALL-ROUNDER',
    },
    {
      fullName: 'Shamim Islam',
      bengaliName: 'শামিম',
      email: 'shamim.bpl@gmail.com',
      contact: '01904174565',
      cat: 'cat-slow-bowl-all',
      bat: 'Right Handed',
      bowl: 'Right Arm Fast',
      currentTeam: 'Brothers Warriors',
      badge: 'WICKET TAKER',
      driveId: '1mVq2nz1fCRo5MlpwZlEYMwabLWkAuMR8',
    },
    {
      fullName: 'Abdullah Al Mamun',
      bengaliName: 'মামুন',
      email: 'mamun.bpl@gmail.com',
      contact: '01815892290',
      cat: 'cat-slow-bowl-all',
      bat: 'Right Handed',
      bowl: 'Right Arm Medium',
      currentTeam: 'The Crown Kings',
      badge: 'ALL-ROUNDER',
      driveId: '1m4N_j9MPlfV6KclND6gz5LyFmUWIjdj7',
    },

    // --- Batting All-Rounder Level-2 (ব্যাটিং অলরাউন্ডার লেভেল-২) ---
    {
      fullName: 'LKD Sadek',
      bengaliName: 'সাদেক',
      email: 'sadek.bpl@gmail.com',
      contact: '01407656394',
      cat: 'cat-bat-all-lvl-2',
      bat: 'Right Handed',
      bowl: 'Right Arm Medium',
      currentTeam: 'Brothers Warriors',
      badge: 'DESTROYER',
      driveId: '109FYXUU8aXVClrxt5q4ayfD4tGenDcTS',
    },
    {
      fullName: 'Roni Khan',
      bengaliName: 'রনি খান',
      email: 'ronikhan.bpl@gmail.com',
      contact: '01753146250',
      cat: 'cat-bat-all-lvl-2',
      bat: 'Right Handed',
      bowl: 'Right Arm Fast',
      currentTeam: 'Brothers Warriors',
      badge: 'HARD HITTER',
      driveId: '1L707lXwXWm0coC9RWYEWfb54qz0abm6A',
    },
    {
      fullName: 'RS Rafiq',
      bengaliName: 'আর এস রফিক',
      email: 'rsboy8437@gmail.com',
      contact: '01679531737',
      cat: 'cat-bat-all-lvl-2',
      bat: 'Right Handed',
      bowl: 'Right Arm Medium',
      currentTeam: 'Brothers Warriors',
      badge: 'ALL-ROUNDER',
      driveId: '16DNMC7FhULPd6dKbpJVtAnaycAHjr-Rq',
    },
    {
      fullName: 'Tusher Hossain',
      bengaliName: 'তুষার',
      email: 'tusher.bpl@gmail.com',
      contact: '01855490339',
      cat: 'cat-bat-all-lvl-2',
      bat: 'Right Handed',
      bowl: 'Right Arm Medium',
      currentTeam: 'Brothers Warriors',
      badge: 'ALL-ROUNDER',
      driveId: '1JMaNSfa2W_k-zauo1ye5eijF6IIJtE5z',
    },
    {
      fullName: 'Jahangir (2)',
      bengaliName: 'জাহাঙ্গীর (২)',
      cat: 'cat-bat-all-lvl-2',
      bat: 'Right Handed',
      bowl: 'Right Arm Medium',
      badge: 'ALL-ROUNDER',
    },
    {
      fullName: 'HK RONY',
      bengaliName: 'এইচ.কে রনি',
      email: 'hkrony62@gmail.com',
      contact: '01613049526',
      cat: 'cat-bat-all-lvl-2',
      bat: 'Right Handed',
      bowl: 'Right Arm Medium',
      currentTeam: 'Prime Brothers Cricket XI',
      badge: 'ALL-ROUNDER',
      driveId: '1qMrXJGidUBuw6YgHtxvIANLPCc5dELhd',
    },

    // =========================================================================
    // SECTION 3: BOWLER AND MINI ALL-ROUNDER (বোলার এবং মিনি অলরাউন্ডার)
    // =========================================================================

    // --- Bowling (বোলিং) ---
    {
      idKey: 'player-asif',
      fullName: 'Asif',
      bengaliName: 'আসিফ',
      email: 'asif.bpl@gmail.com',
      contact: '01623992742',
      cat: 'cat-bowling',
      bat: 'Right Handed',
      bowl: 'Right Arm Fast',
      currentTeam: 'Brothers Warriors',
      badge: 'WICKET TAKER',
      driveId: '1ib3APQq_M9FwAjAiXUIFJES8M_R6hoFd',
    },
    {
      idKey: 'player-mostafiz',
      fullName: 'Md. Mostafizur Rahman',
      bengaliName: 'মোস্তাফিজ',
      email: 'smrocky176@gmail.com',
      contact: '01618214165',
      cat: 'cat-bowling',
      bat: 'Right Handed',
      bowl: 'Right Arm Medium',
      currentTeam: 'The Crown Kings',
      badge: 'DESTROYER',
      driveId: '1RMBb60fpqWvOq9uXXe_riBtN_qT-878e',
    },
    {
      fullName: 'Nahid',
      bengaliName: 'নাহিদ',
      cat: 'cat-bowling',
      bat: 'Right Handed',
      bowl: 'Right Arm Fast',
      badge: 'WICKET TAKER',
    },
    {
      fullName: 'Rifat',
      bengaliName: 'রিফাত',
      cat: 'cat-bowling',
      bat: 'Right Handed',
      bowl: 'Right Arm Fast',
      badge: 'WICKET TAKER',
    },
    {
      fullName: 'Sabbir',
      bengaliName: 'সাব্বির',
      cat: 'cat-bowling',
      bat: 'Right Handed',
      bowl: 'Right Arm Fast',
      badge: 'WICKET TAKER',
    },
    {
      fullName: 'FH Noman',
      bengaliName: 'নোমান',
      email: 'mdnomanahmed16@gmail.com',
      contact: '01857697069',
      cat: 'cat-bowling',
      bat: 'Right Handed',
      bowl: 'Right Arm Fast',
      currentTeam: 'The Crown Kings',
      badge: 'WICKET TAKER',
      driveId: '19IZKmuyBlfmeOL1Iu_UaZ56-3mTp7Iyt',
    },

    // --- Mini All-Rounder (মিনি অলরাউন্ডার) ---
    {
      fullName: 'Raja',
      bengaliName: 'রাজা',
      cat: 'cat-mini-all',
      bat: 'Right Handed',
      bowl: 'Right Arm Medium',
      badge: 'ALL-ROUNDER',
    },
    {
      fullName: 'Robiul',
      bengaliName: 'রবিউল',
      cat: 'cat-mini-all',
      bat: 'Right Handed',
      bowl: 'Right Arm Medium',
      badge: 'GAME CHANGER',
    },
    {
      fullName: 'M Saiful',
      bengaliName: 'সাইফুল',
      email: 'saiful.bpl@gmail.com',
      contact: '01740705002',
      cat: 'cat-mini-all',
      bat: 'Right Handed',
      bowl: 'Right Arm Fast',
      currentTeam: 'The Crown Kings',
      badge: 'WICKET TAKER',
      driveId: '1gSX5kQvd_gEsPFW2SJ0NLhflLvCH5dJi',
    },
    {
      fullName: 'Jahangir (MH)',
      bengaliName: 'জাহাঙ্গীর (MH)',
      cat: 'cat-mini-all',
      bat: 'Right Handed',
      bowl: 'Right Arm Medium',
      badge: 'ALL-ROUNDER',
    },
    {
      fullName: 'Mohammad Nazim',
      bengaliName: 'নাজিম',
      email: 'theking187049@gmail.com',
      contact: '01797591183',
      cat: 'cat-mini-all',
      bat: 'Right Handed',
      bowl: 'None',
      currentTeam: 'Brothers Warriors',
      badge: 'FINISHER',
      driveId: '1XQ0GYCIRvmMWxdn8bxnnTD6TY8stwl6R',
    },
    {
      fullName: 'Monjurul Islam',
      bengaliName: 'মঞ্জুরুল',
      email: 'monjurulcakari@gmail.com',
      contact: '01776651356',
      cat: 'cat-mini-all',
      bat: 'Right Handed',
      bowl: 'Right Arm Fast',
      currentTeam: 'Prime Brothers Cricket XI',
      badge: 'ALL-ROUNDER',
      driveId: '1A9ryMX8z2QCp_OnG5y8wRvnP-wO5ATFJ',
    },

    // --- Official Franchise Captain (Retained) ---
    {
      idKey: 'player-shahin',
      fullName: 'Kazi Shahin',
      bengaliName: 'কাজী শাহিন',
      email: 'kazishahin511@gmail.com',
      contact: '01303768427',
      cat: 'cat-bowl-bat-equal',
      bat: 'Right Handed',
      bowl: 'Right Arm Medium',
      currentTeam: 'Prime Brothers Cricket XI',
      badge: 'CAPTAIN',
      driveId: '1cecWfr-TIMYwQ4lwQWSWVQoOldvdvf7t',
    },
  ];

  const players: Player[] = officialPlayersRaw.map((raw, idx) => {
    const jerseyStr = String(idx + 1).padStart(2, '0');
    const playerId = raw.idKey || `player-${idx + 1}`;
    const photo = raw.driveId ? gDriveImg(raw.driveId) : generateCricketAvatar(raw.fullName, jerseyStr, idx + 1);

    // Check if player is a pre-selected captain of any franchise team
    const teamWithCaptain = teams.find(
      (t) =>
        t.captainPlayerId === playerId ||
        (t.captainName && t.captainName.toLowerCase() === raw.fullName.toLowerCase())
    );
    const isCaptain = !!teamWithCaptain;

    return {
      id: playerId,
      draftId,
      fullName: raw.fullName,
      jerseyNumber: jerseyStr,
      primaryCategoryId: raw.cat,
      playerType: `${raw.bat} • ${raw.bowl}`,
      battingStyle: raw.bat,
      bowlingStyle: raw.bowl,
      badge: isCaptain ? 'CAPTAIN' : raw.badge,
      photoUrl: photo,
      inDraftPool: true,
      contactEmail: raw.email,
      notes: `Bangla: ${raw.bengaliName || raw.fullName}${raw.contact ? ` | Phone: ${raw.contact}` : ''}${raw.currentTeam ? ` | Prev: ${raw.currentTeam}` : ''}`,
      status: isCaptain ? 'drafted' : 'available',
      isCaptain,
      assignedTeamId: teamWithCaptain ? teamWithCaptain.id : undefined,
      assignedCategoryId: isCaptain ? raw.cat : undefined,
      createdAt: now,
      updatedAt: now,
    };
  });

  const draft: Draft = {
    id: draftId,
    name: 'Brothers Premier League (BPL)',
    season: 'Season-2',
    logoUrl: DEFAULT_BPL_LOGO,
    status: 'live',
    currentCategoryId: categories[0].id,
    settings: {
      categoryMode: 'category_by_category',
      animationSpeed: 'normal',
      soundEnabled: true,
      celebrationEnabled: true,
      reducedMotion: false,
      autoSave: true,
    },
    createdAt: now,
    updatedAt: now,
  };

  return {
    draft,
    categories,
    teams,
    players,
  };
}
